### ISSUE TITLE
HunyuanImage-3.0-Instruct推理OOM了

### ISSUE THREAD

**Issue by wjq920615** [Tencent-Hunyuan/HunyuanImage-3.0#71]
按照如下demo code推理报错OOM了，有上面方法减小显存吗？
from modelscope import AutoModelForCausalLM

# Load the model
model_id = "./HunyuanImage-3-Instruct"
# Currently we can not load the model using HF model_id `tencent/HunyuanImage-3.0-Instruct` directly 
# due to the dot in the name.

kwargs = dict(
    attn_implementation="sdpa", 
    trust_remote_code=True,
    torch_dtype="auto",
    device_map="auto",
    moe_impl="eager",   # Use "flashinfer" if FlashInfer is installed
    moe_drop_tokens=True,
)

model = AutoModelForCausalLM.from_pretrained(model_id, **kwargs)
model.load_tokenizer(model_id)

# Image-to-Image generation (TI2I)
prompt = "基于图一的logo，参考图二中冰箱贴的材质，制作一个新的冰箱贴"

input_img1 = "./assets/demo_instruct_imgs/input_1_0.png"
input_img2 = "./assets/demo_instruct_imgs/input_1_1.png"
imgs_input = [input_img1, input_img2]

cot_text, samples = model.generate_image(
    prompt=prompt,
    image=imgs_input,
    seed=42,
    image_size="auto",
    use_system_prompt="en_unified",
    bot_task="think_recaption",  # Use "think_recaption" for reasoning and enhancement
    infer_align_image_size=True,  # Align output image size to input image size
    diff_infer_steps=8, 
    verbose=2
)

# Save the generated image
samples[0].save("image_edit.png")

报错异常如下：
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 59.22 GiB. GPU 0 has a total capacity of 63.59 GiB of which 39.40 GiB is free. Of the allocated memory 21.07 GiB is allocated by PyTorch, and 139.27 MiB is reserved by PyTorch but unallocated. 
以及采用8卡服务器来进行模型并行了：device_map="auto",
但显存还是OOM，请教下如何处理呢？

**Comment by tulvgengenr** [comment]
@wjq920615 @Xxxxxsun 
感谢提问和解答！moe_impl改成flashinfer可以实现更快速度和更少显存。当然，目前moe_impl="eager"也可以支持8卡80G显存推理了，参考我们最近的更新：https://github.com/Tencent-Hunyuan/HunyuanImage-3.0/pull/75

**Comment by coder4nlp** [comment]
8卡还是会OOM

**Comment by tulvgengenr** [comment]
@coder4nlp 麻烦可以给一下具体的显卡型号和执行代码吗？

**Comment by coder4nlp** [comment]
显卡h100，报错是在文本输出万以后，开始生成图片然后OOM
```
from transformers import AutoModelForCausalLM

# Load the model
model_id = "./HunyuanImage-3-Instruct"
# Currently we can not load the model using HF model_id `tencent/HunyuanImage-3.0-Instruct` directly 
# due to the dot in the name.

kwargs = dict(
    attn_implementation="sdpa", 
    trust_remote_code=True,
    torch_dtype="auto",
    device_map="auto",
    moe_impl="eager",   # Use "flashinfer" if FlashInfer is installed
    moe_drop_tokens=True,
)

model = AutoModelForCausalLM.from_pretrained(model_id, **kwargs)
model.load_tokenizer(model_id)

# Image-to-Image generation (TI2I)
prompt = "基于图一的logo，参考图二中冰箱贴的材质，制作一个新的冰箱贴"

input_img1 = "./assets/demo_instruct_imgs/input_1_0.png"
input_img2 = "./assets/demo_instruct_imgs/input_1_1.png"
imgs_input = [input_img1, input_img2]

cot_text, samples = model.generate_image(
    prompt=prompt,
    image=imgs_input,
    seed=42,
    image_size="auto",
    use_system_prompt="en_unified",
    bot_task="think_recaption",  # Use "think_recaption" for reasoning and enhancement
    infer_align_image_size=True,  # Align output image size to input image size
    diff_infer_steps=50, 
    verbose=2
)

# Save the generated image
samples[0].save("image_edit.png")
```

**Comment by coder4nlp** [comment]
如果换成 moe_impl="flashinfer",   # Use "flashinfer" if FlashInfer is installed，输出以下内容好像就卡住了1
```
Assistant: <think>
             do_sample: True
        max_new_tokens: 2048
                 top_k: 1024
                 top_p: 0.95
           temperature: 0.6
    repetition_penalty: 1.0
```

**Comment by tulvgengenr** [comment]
@coder4nlp  麻烦你试一下`run_demo_instruct.sh`这里面的demo cases是否都能正常执行吗，从T2I到单图、多图输入

**Comment by coder4nlp** [comment]
可以运行的

**Comment by tulvgengenr** [comment]
@coder4nlp  您可以试一下，现在transformers的demo代码也可以正常运行了，我们更新了huggingface库的代码： https://huggingface.co/tencent/HunyuanImage-3.0-Instruct/commit/2ec2c78bee7d4b94157341fba86c4c2c7b1858b2

**Comment by coder4nlp** [comment]
请问怎么能加速并节省显存呢，8卡80G，推理一次是90s，时间和显存要求太高了，我看到vllm 文生图示例，没看到编辑示例。

**Comment by davidz123** [comment]
> [@coder4nlp](https://github.com/coder4nlp) 您可以试一下，现在transformers的demo代码也可以正常运行了，我们更新了huggingface库的代码： https://huggingface.co/tencent/HunyuanImage-3.0-Instruct/commit/2ec2c78bee7d4b94157341fba86c4c2c7b1858b2

我也是运行时卡在这里，这次更新可以解决这个问题吗？
Assistant: <think>
             do_sample: True
        max_new_tokens: 2048
                 top_k: 1024
                 top_p: 0.95
           temperature: 0.6
    repetition_penalty: 1.0

**Comment by tulvgengenr** [comment]
@davidz123 可以的
